# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('S', 'single'), ('M', 'multi')], default='S', max_length=1)),
                ('title', models.CharField(max_length=20)),
                ('describe', models.TextField(max_length=500)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('actors', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateTimeField()),
                ('catagory', models.ManyToManyField(to='Tags.Tag')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'serials',
                'get_latest_by': 'created_at',
            },
        ),
    ]
