# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
