# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:37
from __future__ import unicode_literals

import TV_Server.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serials', '0003_serials_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='headshot',
            field=models.ImageField(upload_to=TV_Server.Utils.avator_path),
        ),
    ]
