# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 08:47
from __future__ import unicode_literals

import TV_Server.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serials', '0005_auto_20160428_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=TV_Server.Utils.serials_path),
        ),
    ]
