# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:03
from __future__ import unicode_literals

import TV_Server.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=20)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=TV_Server.Utils.avator_path)),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'manager',
                'get_latest_by': 'created_at',
            },
        ),
    ]
