# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 08:47
from __future__ import unicode_literals

import TV_Server.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Videos', '0002_auto_20161124_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=20)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to=TV_Server.Utils.avator_path)),
                ('videohistory', models.ManyToManyField(to='Videos.Video')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'clients',
                'get_latest_by': 'created_at',
            },
        ),
    ]
