# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Managers', '0001_initial'),
        ('Serials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('describe', models.TextField(blank=True, max_length=500, null=True)),
                ('video_url', models.FileField(upload_to='media')),
                ('play_num', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Managers.Manager')),
                ('serials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serials.Serials')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'video',
                'get_latest_by': 'created_at',
            },
        ),
    ]
