# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Managers.Manager')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'tags',
                'get_latest_by': 'created_at',
            },
        ),
    ]
