# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('device', models.CharField(choices=[('P', 'PC'), ('I', 'IOS'), ('A', 'ANDROID')], default='P', max_length=1)),
                ('sub_comment_id', models.IntegerField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'comments',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients')),
            ],
            options={
                'db_table': 'top',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.Top'),
        ),
    ]
